<%@ page  isErrorPage="true" %>
 <ul id="leftmenu" >
 	<li><a href="python-Basic">About Python</a></li>
 	<li><a href="python-Data-Types">Python Data Type</a></li>
	<li><a href="python-Variable">Python Variable</a></li>
	<li><a href="python-Operators">Python Operators</a></li>
	<li><a href="python-Array">Python Array</a></li>
	<li><a href="python-Input-Output">Python Input Output</a></li>
	<li><a href="python-Control-Statements">Python Control Statements</a>
	<li><a href="python-List">Python List</a>
	<li><a href="python-Set">Python Set</a>
	<li><a href="python-Tuple">Python Tuple</a>
	<li><a href="python-Dictionary">Python Dictionary</a>
	<li><a href="python-Function">Python Function</a>
	<li><a href="python-Class-and-Object">Python Class and Object</a>
	<li><a href="python-Method">Python Method</a>
	<li><a href="python-String">Python String</a>
	<li><a href="python-Inheritance">Python Inheritance</a></li>
	<li><a href="python-Super-Keyword">python Super</a></li>
	<li><a href="python-Polymorphism">Python Polymorphism</a></li>
	<li><a href="python-Encapsulation">python Encapsulation</a></li>
	<li><a href="python-Abstraction">Python Abstraction</a></li>
	<li><a href="python-Packages-Modules">python_Packages_Modules</a></li>
	<li><a href="python-Exception-Handling">Python Exception Handling</a></li>
	<li><a href="python-Regular-Expressions">Python Regular Expressions</a></li>
	<li><a href="python-Database-Connectivity">Python Database Connectivity</a></li>
	<li><a href="python-File-Handling">Python File Handling</a></li>
	<li><a href="python-Networking">Python Networking</a></li>
	<li><a href="python-multithreading">Python Multithreading</a></li>
	<li><a href="python-Numbers">Python Numbers</a></li>
	<li><a href="python-Dates">Python Dates</a></li>
	<li><a href="python-Time">python_Time</a></li>
	<li><b><a href="testing">Testing Link</a></b></li>
 </ul> 
