<%@ page  isErrorPage="true" %>
 <ul id="leftmenu" >
 	<li><a href="python_Basic">About Python</a></li>
 	<li><a href="python_Data_Types">Python Data Type</a></li>
	<li><a href="python_Variable">Python Variable</a></li>
	<li><a href="python_Operators">Python Operators</a></li>
	<li><a href="python_Array">Python Array</a></li>
	<li><a href="python_Input_Output">Python Input Output</a></li>
	<li><a href="python_Control_Statements">Python Control Statements</a>
	<li><a href="python_List">Python List</a>
	<li><a href="python_Set">Python Set</a>
	<li><a href="python_Tuple">Python Tuple</a>
	<li><a href="python_Dictionary">Python Dictionary</a>
	<li><a href="python_Function">Python Function</a>
	<li><a href="python_Class_and_Object">Python Class and Object</a>
	<li><a href="python_Method">Python Method</a>
	<li><a href="python_String">Python String</a>
	<li><a href="python_Inheritance">Python Inheritance</a></li>
	<li><a href="python_Super_Keyword">python Super</a></li>
	<li><a href="python_Polymorphism">Python Polymorphism</a></li>
	<li><a href="python_Encapsulation">python Encapsulation</a></li>
	<li><a href="python_Abstraction">Python Abstraction</a></li>
	<li><a href="python_Exception_Handling">Python Exception Handling</a></li>
	<li><a href="python_Database_Connectivity">Python Database Connectivity</a></li>
	<li><a href="python_Regular_Expressions">Python Regular Expressions</a></li>
	<li><a href="python_Networking">Python Networking</a></li>
	<li><a href="python_multithreading">Python Multithreading</a></li>
	<li><a href="python_Numbers">Python Numbers</a></li>
	<li><a href="python_Dates">Python Dates</a></li>
	<li><a href="python_Time">python_Time</a></li>
	<li><b><a href="testing">Testing Link</a></b></li>
 </ul> 
