<table>
  <tr>
    <th>Data Type</th>
    <th>Flow Control</th>
    <th>Exception</th>
    <th>Object Level</th>
    <th>Method</th>
    <th>Source file</th>
     <th>Modifire</th>
  </tr>
  <tr>
    <td>byte,short,int,long</td>
    <td>if,else</td>
    <td>try,catch</td>
    <td>new</td>
    <td>void</td>
    <td>class</td>
    <td>public,private,protected</td>
 </tr>
 <tr>
    <td>float,double</td>
    <td>switch,case,default</td>
    <td>finally</td>
    <td>this</td>
    <td>return</td>
    <td>extends</td>
    <td>final</td>
 </tr>
 <tr>
    <td>char</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
 </tr>
</table>


 <h6><b>what is implicit?</b></h6>
 <p>done by jvm.not the programmer</p>
 
 <h6><b>what is explicit?</b></h6>
 <p>done by the programmer</p>
 


<h6><b>Widening Casting</b></h6>
<pre>
<p>byte->short->int->long->float->-double</p>
</pre>
<h6><b>Narrowing Casting</b></h6>
<pre>
<p>double->float->long->int->short->byte</p>
</pre>
<h1>What is hash code?</h1>
<p>unique identification number of object.every object contact Hashcode.
Hashcode is hexadecimal number generated by JVM to identify the object unique.</p>
 <!-- The End  -->
 
 
 